name: more is less
favicon: null
layout_spectrum: 0.6620868353638798
typography_spectrum: 0.4619373148307204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111016'
    - '#eee1bf'
    - '#826257'
    - '#ea659c'
    - '#791f3b'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
