name: more is less
favicon: null
layout_spectrum: 0.6620868353638798
typography_spectrum: 0.4619373148307204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7678077809978276
  lightness: 0.6874227179214358
  saturation: 0.1855465543922037
  rhythmicContrast: 0.32416929421015084
purpose: []
